//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class IQC
{
    public int 編號 { get; set; }
    public Nullable<System.DateTime> 上傳日期 { get; set; }
    public Nullable<System.DateTime> 檢驗日期 { get; set; }
    public string 料號 { get; set; }
    public string 品名 { get; set; }
    public string 圖號 { get; set; }
    public string 圖面版次 { get; set; }
    public string 檢驗標準書 { get; set; }
    public string 供應商代號 { get; set; }
    public string 供應商名稱 { get; set; }
    public string 進貨單號 { get; set; }
    public string 樣本數 { get; set; }
    public Nullable<double> 收貨數 { get; set; }
    public Nullable<double> 檢驗項目 { get; set; }
    public string 規格範圍 { get; set; }
    public string 備註 { get; set; }
    public Nullable<double> 規格下限 { get; set; }
    public Nullable<double> 中心值 { get; set; }
    public Nullable<double> 規格上限 { get; set; }
    public string 單位 { get; set; }
    public Nullable<double> 工件No { get; set; }
    public string 量測值 { get; set; }
    public string 判定 { get; set; }
    public string 量測儀器 { get; set; }
    public string 原料單號 { get; set; }
}

public partial class user
{
    public string 帳號 { get; set; }
    public string 密碼 { get; set; }
    public string 姓名 { get; set; }
    public string 權限 { get; set; }
}
